/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import dal.DAO;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.entities.Livro;

/**
 *
 * @author gille
 */
public class Emprestar extends javax.swing.JInternalFrame {

    ConsultarLivros consultarLivros = new ConsultarLivros();
    Livro livro;

    /**
     * Creates new form CadLivro
     */
    public Emprestar() {
        initComponents();

        try {
            this.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Emprestar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Emprestar(Livro livro) {
        initComponents();

        try {
            this.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Emprestar.class.getName()).log(Level.SEVERE, null, ex);
        }

//        edtCpf.setText();
//        edtCpf.setEnabled(false);
        edtIsbn.setText(livro.getISBN());
//        edtDtEmp.setText();
//        edtDtDev.setText();
//        edtNome.setText();
        edtTitulo.setText(livro.getTitulo());
        edtCpf.requestFocus();
//        btnSalvar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIsbn = new javax.swing.JLabel();
        lblDtEmp = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        lblDtDev = new javax.swing.JLabel();
        edtDtDev = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        edtTitulo = new javax.swing.JTextField();
        edtCpf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edtIsbn = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        edtDtEmp = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1193, 600));

        lblIsbn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIsbn.setText("ISBN:");

        lblDtEmp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDtEmp.setText("Data Empréstimo:");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblDtDev.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDtDev.setText("Data Devolução:");

        edtDtDev.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtDtDev.setEnabled(false);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setText("Nome:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Título:");

        edtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtTitulo.setEnabled(false);

        edtCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empréstimo");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        edtIsbn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtIsbn.setEnabled(false);

        lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCpf.setText("CPF:");

        edtDtEmp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtDtEmp.setEnabled(false);

        edtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtNome.setEnabled(false);

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edtIsbn)
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIsbn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCpf)
                            .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtDtDev)
                    .addComponent(edtDtEmp)
                    .addComponent(lblDtDev, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDtEmp, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGap(528, 528, 528)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(538, 538, 538))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDtEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtDtEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDtDev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtDtDev, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscar, btnSalvar, edtCpf, edtDtDev, edtDtEmp, edtIsbn, edtNome, edtTitulo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Livro setarLivro() {
        livro = new Livro();

        livro.setISBN(edtCpf.getText().trim());
        livro.setTitulo(edtIsbn.getText().trim());
        livro.setAutor(edtDtEmp.getText().trim());
        livro.setCategoria(edtDtDev.getText().trim());
        livro.setAno(edtNome.getText().trim());
        livro.setEditora(edtTitulo.getText().trim());

        return livro;
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (edtCpf.getText().trim().isEmpty() || edtIsbn.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
            edtCpf.requestFocus();
            return;
        }

        DAO dao = new DAO();
        Livro livro = setarLivro();

        if (dao.conectar()) {
            int status = dao.salvarLivro(livro);
            switch (status) {
                case 1 -> {
                    JOptionPane.showMessageDialog(null, "Dados inseridos com Sucesso");
                    limpar();
                }
                case 1062 ->
                    JOptionPane.showMessageDialog(null, "Código do livro já cadastrado");
                default ->
                    JOptionPane.showMessageDialog(null, "Erro ao tentar cadastrar\nCódigo do erro: " + status);
            }
            dao.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "Erro na Conexão com o Banco de Dados");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void limpar() {
        edtCpf.setText(null);
        edtIsbn.setText(null);
        edtDtEmp.setText(null);
        edtDtDev.setText(null);
        edtNome.setText(null);
        edtTitulo.setText(null);
        edtCpf.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtDtDev;
    private javax.swing.JTextField edtDtEmp;
    private javax.swing.JTextField edtIsbn;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDtDev;
    private javax.swing.JLabel lblDtEmp;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
