/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gille
 */
public class Main extends javax.swing.JFrame {

    ConsultarLivros consultarLivros = new ConsultarLivros();
    ConsultarPessoas consultarPessoas = new ConsultarPessoas();
    CadLivro cadLivro = new CadLivro();
    CadPessoa cadPessoa = new CadPessoa();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
                
        consultarLivros.setVisible(true);
        desktop.add(consultarLivros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmCadLivro = new javax.swing.JMenuItem();
        itmCadPessoa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmConsultarLivro = new javax.swing.JMenuItem();
        itmConsultarPessoa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boa Biblioteca");
        setResizable(false);

        desktop.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1193, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastrar");

        itmCadLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itmCadLivro.setText("Livro");
        itmCadLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadLivroActionPerformed(evt);
            }
        });
        jMenu1.add(itmCadLivro);

        itmCadPessoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itmCadPessoa.setText("Solicitante");
        itmCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(itmCadPessoa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        itmConsultarLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmConsultarLivro.setText("Livros");
        itmConsultarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultarLivroActionPerformed(evt);
            }
        });
        jMenu2.add(itmConsultarLivro);

        itmConsultarPessoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmConsultarPessoa.setText("Solicitantes");
        itmConsultarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultarPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(itmConsultarPessoa);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(1209, 662));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadLivroActionPerformed
        // TODO add your handling code here:
 
        
        desktop.removeAll();

        cadLivro.setVisible(true);
        desktop.add(cadLivro);
    }//GEN-LAST:event_itmCadLivroActionPerformed

    private void itmConsultarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsultarLivroActionPerformed
        // TODO add your handling code here:

        desktop.removeAll();
        
        consultarLivros.setVisible(true);
        desktop.add(consultarLivros);
    }//GEN-LAST:event_itmConsultarLivroActionPerformed

    private void itmCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadPessoaActionPerformed
        // TODO add your handling code here:

        
        desktop.removeAll();
        
        cadPessoa.setVisible(true);
        desktop.add(cadPessoa);
    }//GEN-LAST:event_itmCadPessoaActionPerformed

    private void itmConsultarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsultarPessoaActionPerformed
        // TODO add your handling code here:           

        
        desktop.removeAll();

        consultarPessoas.setVisible(true);
        desktop.add(consultarPessoas);
    }//GEN-LAST:event_itmConsultarPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem itmCadLivro;
    private javax.swing.JMenuItem itmCadPessoa;
    private javax.swing.JMenuItem itmConsultarLivro;
    private javax.swing.JMenuItem itmConsultarPessoa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
